version: "3"

services:
  vnc:
    image: accetto/ubuntu-vnc-xfce-firefox-g3
    restart: unless-stopped
    #environment:
    #  - VNC_PW=
    #  - VNC_RESOLUTION=1024x768
    ports:
      - 6901:6901
    volumes:
      - "./Downloads:/home/headless/Downloads"
    shm_size: "2gb"
    cap_add:
      - SYS_ADMIN